const ExampleHut = {
  display_name: 'Aarbiwak SAC',
  en_translation_ok: true,
  fr_translation_ok: true,
  geographical_name: 'Aarbiwak SAC',
  geom: {
    type: 'Point',
    coordinates: [2654722, 1156279]
  },
  gis_geometry_ok: false,
  id: 2147000001,
  is_private: false,
  it_translation_ok: true,
  main_lang: 'en',
  nvp_ok: false,
  orig_status: null,
  fax: null,
  tel: null,
  url: 'http://www.sac-pilatus.ch',
  email: 'k.brefin@livenet.ch',
  owner: 'SAC PILATUS',
  hrs_id: 603,
  sac_id: 1,
  sleeps: 17,
  opening: {
    month_01: 0,
    month_02: 1,
    month_03: 2,
    month_04: 0,
    month_05: 0,
    month_06: 0,
    month_07: 0,
    month_08: 0,
    month_09: 0,
    month_10: 0,
    month_11: 0,
    month_12: 0
  },
  catering: {
    month_01: 2,
    month_02: 2,
    month_03: 2,
    month_04: 2,
    month_05: 2,
    month_06: 2,
    month_07: 2,
    month_08: 2,
    month_09: 2,
    month_10: 2,
    month_11: 2,
    month_12: 2
  },
  opentext: {
    de: 'Kein Mobiltelefonempfang, nur Notfunkanlage',
    en: null,
    fr: "Pas de connexion téléphonique, uniquement réseau d'urgence",
    it: null
  },
  services: {
    drinks: true,
    internet: false,
    not_paid: false,
    css_rebate: false,
    half_board: false,
    plain_meals: false,
    family_rooms: false,
    payment_mobile: false,
    cooking_catered: true,
    dogs_on_request: false,
    payment_creditcard: false,
    cooking_non_catered: true,
    separable_group_rooms: false
  },
  suitable: {
    family: false,
    climbing: false,
    alpine_tour: false,
    via_ferrata: false,
    climbing_kids: false,
    mountain_hiking: true,
    ski_snowboard_tour: true
  },
  addresses: [],
  tourism_id: null,
  name_internet: 'Capanna Lego',
  association_id: 3,
  emergency_shelter: 12,
  photos: [],
  regions: [{ region_id: 5 }],
  regions_denormalization: 'Ticino',
  reviewer_ok: false,
  small_changes_ok: false,
  status: 'published',
  type: 'hut',
  version: 1,
  nb_routes: 8
} as const;

export type HutTypeApi = typeof ExampleHut;
